Milestone 3: Game logic
LoboArkano/Tic-Tac-Toe pull request #3
Opened 2020-04-27 20:25 UTC by LoboArkano

Develop rules to establish win and draw conditions, prevent a player from choosing an invalid position. Also prints and updates the board after a player's choice.
Created Board class:
- Methods: example, instructions, update_move, row_position and column_position
Created Player class:
- Methods: N/A
Created Rules class:
- Methods: in_range?, untaken?, previous_choice?, valid_move, win_check and draw_check

2020-04-28 00:28 UTC, majovanilla requested changes
Hey @LoboArkano , 👋

## You did a *great* job on this project! 💜 

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- You should keep your code more organized. I gave you some tips below to achieve this. Please implement them.

- Remember to keep most of your code inside methods, to avoid repetition and also for security reasons. It's always better to create one method and call it multiple times than put the same code multiple times. I gave you some instructions on this, too.

## Please, make all the changes requested on the comments below and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +end
This should not be here but on the board class. Please create a method there and you can call it there, after.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +print_board.call(game_board.board)
Here, instead of calling the proc, you call the method.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +p2 = Player.new(input)
You are not validating the players' names. If I click `enter`, I can add two empty names to the game and that is not good in terms of the UX.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
>      end
This should be in a winner method on the player Class. You can leave the if, but put the rest of the code on a method, cause you are calling it twice, so there is no need to repeat it.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +    end
Call the winner method mentioned above.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +    turn += 1
You are repeating this code for player 1 and player 2. It is better to create a method and then call it for both of the players to keep your code DRY.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +    turn += 1
use the method commented on lines 56-60 instead of repeating your code

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +  print_board.call(game_board.board)
Call the method that prints the board instead of the proc.
The board you print when the game has started doesn't have the numbers on each cell. It's easier for the players if you give them the numbers, so they can choose the cell easily.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +print_board.call(game_board.board)
Call the method that prints the board instead of the proc.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +  if victory || draw # rubocop:disable Style/Next
please don't disable rubocop. Instead, try to understand what you are not doing in the best way and fix it. Remember that the purpose of the linters is to remember you the best practices.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
>      elsif draw == true
There is no need to check line 80 and then check on line 81 and 84. You know that your `victory` and `draw` variables exist and that they are false, so just check if they are `true` instead of creating a nested `if statement`.

To make your code better (and not have accessible variables like victory and draw), you can create a method to check and another to modify those variables and just return their value, so then you can check here.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +    elsif input.include?('Y') || input.include?('y')
This should be another method. You can call it check_restart. You can put it on the game Class and call it here.
There is no need to check if it's an upper case or lower case if you convert the input to one of them from the beginning.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
>      end
This should be a private method on the Game Class that you call on check_restart. You can call it restart_game.

2020-04-28 00:28 UTC, majovanilla commented on lib/game.rb
> +end
Create a file for each class and put it in the lib folder. That keeps your code more organized.

2020-04-28 00:28 UTC, majovanilla commented on lib/game.rb
> +end
Create a file for each class and put it in the lib folder. That keeps your code more organized.

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
> +puts 'Choice a number between 1 and 9'
It should say: 'Choose a number  between 1 and 9'

2020-04-28 00:28 UTC, majovanilla commented on bin/main.rb
>      input = gets.chomp
When you choose to play again, the board is not displayed for the first move. Please make the adjustments to print it so the players know what to click.

2020-04-29 21:12 UTC, kobiyoyo requested changes
## Hi @LoboArkano      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, Just few things to work on. 
### General
- [x] The last move isnt displayed on the board lets fix that.
![1](https://user-images.githubusercontent.com/23278161/80647445-63918580-8a66-11ea-8a08-d8d25508aa9c.png)
Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-29 21:12 UTC, kobiyoyo commented on lib/game.rb
> +    puts "#{player.name} choose #{player.choices[-1]}"
No puts/print and get.chomp outside main.rb file

2020-04-29 21:12 UTC, kobiyoyo commented on lib/board.rb
> +      end
No puts/print and get.chomp outside main.rb file.

2020-04-30 11:49 UTC, maelfosso approved these changes
# Congratulations :clap: 

It's Ok :+1: You can merge it now :smile: 
Good continuation :handshake: 

Mael FOSSO

2020-04-30 11:49 UTC, maelfosso commented on lib/game.rb
> +    @victory_rows = [%w[1 2 3], %w[4 5 6], %w[7 8 9], %w[1 4 7], %w[2 5 8], %w[3 6 9], %w[1 5 9], %w[3 5 7]]
**`[OPTIONAL]`** It could be better to define it as a CONSTANT

2020-04-30 16:56 UTC, merged